
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 316316
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false # 关闭驼峰命名规则（匹配下划线字段名）不建议关闭，不然实体类都得注释映射，优化主键命名，后续改一下



Logging:
  level:
    com.wms: debug